hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl dispatch workspace 5")
    hl.exec_cmd("$HOME/.dotfiles/LMD/modules/hyprpaper/hyprpaper/hyprpaper-reloader.sh")
    -- hl.exec_cmd("quickshell -c $HOME/.dotfiles/LMD/modules/qs/hyprbar")
    hl.exec_cmd("eww open hyprbar")
    hl.exec_cmd("playerctld daemon")
    hl.exec_cmd("quadcastrgb solid -b 0")
    hl.exec_cmd("hyprctl setcursor HyprCross 25")
end)
