return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		lazy = false,
		main = "nvim-treesitter",
		opts = {
			ensure_installed = {
				"lua",
				"rust",
				"c",
				"java",
				"bash",
				"yaml",
				"toml",
				"json",
				"dockerfile",
				"markdown",
				"vim",
				"vimdoc",
			},
			auto_install = true,
			highlight = { enable = true },
			indent = { enable = true },
			textobjects = {
				select = {
					enable = true,
					lookahead = true,
					keymaps = {
						["af"] = "@function.outer",
						["if"] = "@function.inner",
						["ac"] = "@class.outer",
						["ic"] = "@class.inner",
						["aa"] = "@parameter.outer",
						["ia"] = "@parameter.inner",
						["ab"] = "@block.outer",
						["ib"] = "@block.inner",
						["al"] = "@loop.outer",
						["il"] = "@loop.inner",
						["ai"] = "@conditional.outer",
						["ii"] = "@conditional.inner",
						["ak"] = "@call.outer",
						["ik"] = "@call.inner",
						["ar"] = "@return.outer",
						["ir"] = "@return.inner",
						["as"] = "@statement.outer",
						["ax"] = "@assignment.outer",
						["ix"] = "@assignment.inner",
						["lx"] = "@assignment.lhs",
						["rx"] = "@assignment.rhs",
						["ao"] = "@comment.outer",
					},
				},
				move = {
					enable = true,
					goto_next_start = {
						["]f"] = "@function.outer",
						["]c"] = "@class.outer",
						["]l"] = "@loop.outer",
						["]i"] = "@conditional.outer",
						["]k"] = "@call.outer",
						["]r"] = "@return.outer",
					},
					goto_next_end = {
						["]F"] = "@function.outer",
						["]C"] = "@class.outer",
					},
					goto_prev_start = {
						["[f"] = "@function.outer",
						["[c"] = "@class.outer",
						["[l"] = "@loop.outer",
						["[i"] = "@conditional.outer",
						["[k"] = "@call.outer",
						["[r"] = "@return.outer",
					},
					goto_prev_end = {
						["[F"] = "@function.outer",
						["[C"] = "@class.outer",
					},
				},
			},
		},
	},
	{
		"nvim-treesitter/nvim-treesitter-textobjects",
		dependencies = { "nvim-treesitter/nvim-treesitter" },
	},
}
