palette = 'mine'
add_newline = false

format = """
$username\
[](fg:bg1 bg:bg2)\
$directory\
[](fg:bg2 bg:bg3)\
$git_branch\
$git_status\
[](fg:bg3 bg:bg4)\
$rust\
$lua\
$c\
$java\
$maven\
[](fg:bg4 bg:bg5)\
$cmd_duration\
[ ](fg:bg5)
$character
"""

[character]
success_symbol = "[](#cba6f7)"
error_symbol = "[](#f38ba8)"

[username]
show_always = true
style_user = "fg:fg1 bg:bg1"
style_root = "fg:fg1 bg:bg1"
format = "[ $user ]($style)"

[directory]
style = "fg:fg2 bg:bg2"
format = "[ $path ]($style)"
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ""
style = "fg:fg3 bg:bg3"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:fg6 bg:bg3"
format = "[$all_status$ahead_behind ]($style)"

[rust]
symbol = ""
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[lua]
symbol = "󰢱"
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[c]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[cpp]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = " "
style = "fg:fg4 bg:#06969A"
format = "[ $symbol $context ]($style)"

[elixir]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[elm]
symbol = " "
style = "bg:bg4"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[gradle]
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[haskell]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[julia]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[maven]
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = ""
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[bun]
symbol = ""
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[nim]
symbol = "󰆥 "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[scala]
symbol = " "
style = "fg:fg4 bg:bg4"
format = "[ $symbol ($version) ]($style)"

[cmd_duration]
min_time = 1000  # Only show if the command took 2 seconds or longer (in milliseconds)
style = "fg:fg5 bg:bg5"
format = "[ 󱎫 $duration ]($style)"

[palettes.mine]
bg1 = "#0671b7"
bg2 = "#67a3d9"
bg3 = "#8ebdde"
bg4 = "#f8b7cd"
bg5 = "#f298b4"


fg1 = "#f0f2ff"
fg2 = "#f0f2ff"
fg3 = "#f0f2ff"
fg4 = "#f0f2ff"
fg5 = "#f0f2ff"
fg6 = "#f0f2ff"
