add_newline = false
format = '$all'
palette = 'catppuccin_mocha'

[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
style = "blue"

[bun]
format = '\[[$symbol($version)]($style)\]'
style = "red"

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
style = "blue"

[cmake]
format = '\[[$symbol($version)]($style)\]'
style = "blue"

[cmd_duration]
format = '\[[$duration]($style)\]'
style = "peach"

[conda]
format = '\[[$symbol$environment]($style)\]'
style = "green"

[directory]
style = "blue"
truncation_length = 1
fish_style_pwd_dir_length = 1

[docker_context]
format = '\[[$symbol$context]($style)\]'
style = "blue"

[git_branch]
format = '\[[$symbol$branch]($style)\]'
style = "mauve"

[git_status]
format = '(\[[$all_status$ahead_behind]($style)\])'
style = "maroon"

[golang]
format = '\[[$symbol($version)]($style)\]'
style = "sky"

[lua]
format = '\[[$symbol($version)]($style)\]'
style = "blue"

[nodejs]
format = '\[[$symbol($version)]($style)\]'
style = "green"

[os]
format = '\[[$symbol]($style)\]'
style = "blue"

[package]
format = '\[[$symbol$version]($style)\]'
style = "peach"

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "white"

[rust]
format = '\[[$symbol($version)]($style)\]'
style = "red"

[java]
format = '\[[$symbol($version)]($style)\]'
style = "red"

[time]
format = '\[[$time]($style)\]'
style = "peach"

# --- Color Palette ---

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
